spring:
  application:
    name: dubbo-api-provider1
#dubbo:
#  registry:
#    protocol: zookeeper
#    address: localhost:2181
#    id: lin-registry-1
#  application:
#    name: dubbo-api-provider-demo1
#    id: dubbo-api-provider-id1
#    qos-enable: true
#  scan:
#    basePackages: me.peyppicp.service.api.impl
#  protocol:
#    name: dubbo
#    id: dubbo
#    status: server
#    port: -1
demo:
  service:
    version: 1.0